const mongoose = require('mongoose');

const EnrollmentSchema = new mongoose.Schema({
  learnerReferenceNumber: { type: String, required: true },
  surname: { type: String, required: true },
  firstName: { type: String, required: true },
  middleName: String,
  extension: String,
  dateOfBirth: Date,
  placeOfBirth: String,
  sex: String,
  age: String,
  religion: String,
  citizenship: String,
  houseNumber: String,
  street: String,
  barangay: String,
  city: String,
  province: String,
  zipCode: String,
  contactNumber: String,
  emailAddress: String,
  lastSchoolAttended: String,
  schoolAddress: String,
  gradeLevel: String,
  schoolYear: String,
  fatherName: String,
  fatherOccupation: String,
  fatherContactNumber: String,
  motherName: String,
  motherOccupation: String,
  motherContactNumber: String,
  guardianName: String,
  guardianRelationship: String,
  guardianOccupation: String,
  guardianContactNumber: String,
  emergencyContactName: String,
  emergencyContactRelationship: String,
  emergencyContactNumber: String,
  emergencyContactAddress: String,
  gradeToEnroll: String,
  strand: String,
  track: String,
  birthCertificate: Boolean,
  form137: Boolean,
  form138: Boolean,
  goodMoral: Boolean,
  medicalCertificate: Boolean,
  specialNeeds: String,
  allergies: String,
  medications: String,
  agreementAccepted: Boolean,
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Enrollment', EnrollmentSchema);
